name: Generar build y despliegue en GitPage
on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build a ramas develop o main
    steps:
      - name: Git-checkout
        uses: actions/checkout@v3

      - name: Instalación de todas las dependencias
        run: npm install

      - name: Build
        run: npm run build # The build command of your project
        env:
          CI: false
          VITE_EMAILJS_USER_ID: ${{ secrets.VITE_EMAILJS_USER_ID }}
          VITE_EMAILJS_SERVICE_ID: ${{ secrets.VITE_EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: ${{ github.ref == 'refs/heads/main' && 'build-main' || 'build-dev' }}
          FOLDER: build/dist # Directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build ({sha}): {msg}"
